#!/bin/bash
#
# Example abusage:
# free-ollama gemma3:latest {0..10}
#
# It's a stack based system with the syntax
# [model-name [index ... ]]*
# You can omit the index to see all of them.
#
# The column output is space delimetered so you can 
#
# $ free-ollama model1 model2 | sort -rn | cut -d ' ' -f 1-2 | xargs -d '\n' -I {} redis-cli rpush server-pool "{}"
#
# And now you have a server pool. You can even "test" it.
# 
# $ free-ollama test model1
#
# Try instrumenting it with llcat, then maybe xpanes
#
# Don't know what to choose?
# Run it without arguments, you'll get a frequency distribution.
#

db="$HOME/.cache/free-ollama.json"

cache() {
    if [[ ! -f "$db" ]] || [[ -n "$(find "$db" -mmin +1440)" ]]; then
        echo "Updating cache..." > /dev/stderr
        curl -Ls 'https://awesome-ollama-server.vercel.app/data.json' > $db
    fi
}

process_stack() {
   [[ -z "$model" ]] && return
   jq -r 'map(select(.models and (.models | contains(["'$model'"])))) 
       | sort_by(.tps) 
       | .['$(IFS=,; echo "${index[*]}")'] 
       | "\(.tps | floor) \(.server) \(.models 
            | map(select(contains("'$model'"))) 
            | join(" ")) "' "$db"

   index=()
}

tester() {
    bad="$HOME/.cache/free-ollama-bad-hosts.txt" 
    touch "$bad"
    if [[ -n "$dotest" ]]; then
        tac | grep -vf "$bad" | while read tps host model; do
            # The < /dev/null is to avoid llcat from slurping up the stdin
            timing=$( { 
                time timeout 30s llcat -u $host -m $model "respond with test" </dev/null >~/.cache/free-ollama.test 2>&1; 
            } 2>&1 | grep real | sed 's/[a-z\ ]//g' )
            if [[ -s ~/.cache/free-ollama.test ]]; then 

                if [[ -n "$1" ]]; then
                    echo "$host"
                    return
                fi

                printf "%s %-30s %s\n" $timing $host $model
            else 
                if [[ -z "$1" ]]; then
                    echo "Bad -- $host $model"
                    echo "$host $model" >> "$bad"
                fi
            fi
        done
    else
        cat
    fi
}

cache
if [[ -z "$1" ]]; then
    jq -r 'map(.models[]) | group_by(.) | map("\(length) \(.[0])") | .[]' "$db" | sort -n
else
    declare -a index
    model=
    while [ $# -gt 0 ]; do
        case $1 in
            --proxy) start=11434
                arg="$2"
                if [[ ! "$arg" =~ /http/ ]]; then
                    model="$2"
                    dotest=1
                else
                    host="$2"
                fi

                while true; do
                    if [[ "$dotest" == 1 ]]; then
                        echo " 👀 to pet a $model"
                        host=$(process_stack | tester 1)
                    fi
                    while true; do
                        echo " $host -> 127.0.0.1:$start"
                        socat TCP-LISTEN:$start,fork,reuseaddr TCP:${host#*://} 
                        [[ $? != 1 ]] && break
                        echo " \_ Woops :$start is in use"
                        (( start++ ))
                    done
                    echo
                    read -p "Enter for next, ctrl+c to exit..."
                done
                exit
                ;;
            --refresh) rm ~/.cache/free-ollama*.*; cache; echo "Ahh! How refreshing";;
            --help) $(command -v batcat || echo cat) "$0" ;;
            test) dotest=1 ;;
            [0-9]*) index+=( "$1" ) ;;
            *) process_stack | tester; model=$1 ;;
        esac
        shift
    done
    process_stack |tester
fi
