#!/bin/bash
#
# Pet the feral llama
#
#   \\         
#    l'> Bahhhhh
#    ll       
#    llama~  
#    || ||  
#    '' ''
#
# Example abusage:
#
# free-ollama gemma3:latest {0..10}
#
# It's a stack based system with the syntax
# [model-name [index ... ]]*
# You can omit the index to see all of them.
#
# The column output is space delimetered so you can 
#
# $ free-ollama model1 model2 | sort -rn | cut -d ' ' -f 1-2 | xargs -d '\n' -I {} redis-cli rpush server-pool "{}"
#
# And now you have a server pool. You can even "test" it.
# 
# $ free-ollama --test model1
#
# Try instrumenting it with llcat, then maybe xpanes
#
# Don't know what to choose?
# Run it without arguments, you'll get a frequency distribution.
#

db="$HOME/.cache/free-ollama.json"
_host=
_mas=

cache() {
    if [[ ! -f "$db" ]] || [[ -n "$(find "$db" -mmin +1440)" ]]; then
        echo "Updating cache..." > /dev/stderr
        curl -Ls 'https://awesome-ollama-server.vercel.app/data.json' > $db
    fi
}

process_stack() {
    local out=' "\(.tps | floor) \(.server) \(.models 
            | map(select(contains("'$model'"))) 
            | join(" ")) "' 
    [[ -z "$model" ]] && return
    [[ "$model" =~ cloud ]] && nocloud= || nocloud='and (.models | all(contains(":cloud") | not))'

    if [[ -n "$_host" ]]; then 
        ## MAS format https://day50.dev/mas.html
        if [[ -n "$_mas" ]]; then
            out='"\(.server)#m='$model'"'
        else
            out='"\(.server)"'
        fi
    fi

    jq -r 'map(
       select( .models 
               and (.models | contains(["'$model'"]))
               and (.models | all(contains(":cloud") | not))
               '"$nocloud"'
           )
       ) 
       | sort_by(.tps) 
       | .['$(IFS=,; echo "${index[*]}")'] 
       | '"$out" "$db"

   index=()
}

curly() {
    curl -d '{"model":"'$4'","messages":[{"role":"user","content":"'$5'\n"}]}' $2 2>&1
}

tester() {
    pet=-1
    skip=${1:-0}
    bad="$HOME/.cache/free-ollama-bad-hosts.txt" 
    touch "$bad"
    if [[ -n "$dotest" ]]; then
        tester=llcat
        if ! command -v llcat > /dev/null 2>&1; then
            if command -v uv > /dev/null 2>&1; then
                tester="uvx llcat"
            elif ! command curl > /dev/null 2>&1; then
                tester=curly
            else
                echo "You need llcat or uv or curl to test."
                echo
                echo "First of all, what the fuck is wrong with you? Is this how you live?"
                echo
                echo "Second, do one of these:"
                echo
                echo " * pipx install llcat"
                echo " * uv tool install llcat"
                echo " * pip install llcat (probably won't work but you do you)"
                exit 1
            fi
        fi

        tac | grep -vFf "$bad" | while read tps host model; do
            (( pet ++ ))
            (( pet < skip )) && continue 

            # The < /dev/null is to avoid llcat from slurping up the stdin
            start_time=$(date +%s.%N)
            model=${model%% *}
            timeout 90s $tester -u $host -m $model "respond with the single word 'test'" </dev/null > ~/.cache/free-ollama.test 2>&1
            end_time=$(date +%s.%N)
            timing=$( echo "$end_time - $start_time" | bc )

            if [[ -s ~/.cache/free-ollama.test ]] && ! grep -iE '(fail|error)' ~/.cache/free-ollama.test > /dev/null; then 

                if [[ -n "$1" ]]; then
                    if [[ "$info" == 1 ]]; then 
                        echo " Looking under the hood!" > /dev/stderr
                        if [[ $tester != 'curly' ]]; then
                            $tester -u $host -m $model --info </dev/null | jq . > /dev/stderr
                            echo > /dev/stderr
                        fi
                    fi
                    echo "$host"
                    return
                fi

                printf "%s %s#m=%s\n" ${timing:0:4} $host $model
               
            else 
                jq .data.response.payload.error.message ~/.cache/free-ollama.test >/dev/stderr
                echo "  🐡  Not friendly! $host#m=$model" > /dev/stderr
                [[ -n "$host" && -n "$model" ]] && echo "$host $model" >> "$bad"
            fi
        done
    else
        cat
    fi
}

proxy() {
    local start=11434
    local pet=0
    if [[ ! "$1" =~ /http/ ]]; then
        model="$1"
        dotest=1
    else
        host="$1"
    fi

    while true; do
        if [[ "$dotest" == 1 ]]; then
            echo " 👀 to pet a $model"
            host=$(process_stack | tester $pet)
            if [[ -z "$host" ]]; then
                echo -e " 🌵 There doesn't seem to be any good hosts!\n    Check ~/.cache/free-ollama-bad-hosts.txt"
                exit 1
            fi
        fi
        while true; do
            echo " $host -> 127.0.0.1:$start"

            if command -v socat > /dev/null 2>&1; then
                socat TCP-LISTEN:$start,fork,reuseaddr TCP:${host#*://} 
            else
                echo "You need socat for the proxy."
            fi

            [[ $? != 1 ]] && break
            echo " \_ Woops :$start is in use"
            (( start++ ))
        done
        echo
        read -p " Press Enter for more 🦙. Ctrl+C to leave the park..."
        (( pet++ ))
    done
    exit
}

cache
if [[ -z "$1" ]]; then
    jq -r 'map(.models[]) | group_by(.) | map("\(length) \(.[0])") | .[]' "$db" | sort -n
else
    declare -a index
    model=
    while [ $# -gt 0 ]; do
        case $1 in
            --host) _host=1 ;;
            --mas)  _mas=1 _host=1 ;;
            --info) info=1 ;;
            --proxy) proxy $2 ;;
            --update|--refresh) rm ~/.cache/free-ollama*.*; cache; echo "Ahh! How refreshing";;
            --help) $(command -v batcat || echo cat) "$0" ;;
            --test) dotest=1 ;;
            *[A-Za-z]*) process_stack | tester; model=$1 ;;
            [0-9]*) index+=( "$1" ) ;;
        esac
        shift
    done
    process_stack | tester 
fi
