#!/usr/bin/env bash
export OLLAMA_HOST="$2" 
model="$1"
if [[ $(ollama ps | wc -l) == 1 ]]; then
    if [[ $(ollama ls | grep "$model" | wc -l) -gt 0 ]]; then
        echo "<<<"
        ollama ls | grep "$model"
        echo ">>>"
        res=$(timeout 120s ollama run "$model" "respond with the word test")
        grep -iE test <(echo $res) && echo "$2 - passed" || ollama rm $1
    else
        echo "Model not on $OLLAMA_HOST"
    fi
else
    echo "Skipping $OLLAMA_HOST"
fi
